import type { VideoType, CategoryType, CommentType, StudioType } from "./types"

export const categories: CategoryType[] = [
  { id: "trending", name: "Trending" },
  { id: "action", name: "Action" },
  { id: "comedy", name: "Comedy" },
  { id: "drama", name: "Drama" },
  { id: "sci-fi", name: "Sci-Fi" },
  { id: "horror", name: "Horror" },
  { id: "documentary", name: "Documentary" },
  { id: "animation", name: "Animation" },
  { id: "thriller", name: "Thriller" },
  { id: "romance", name: "Romance" },
  { id: "fantasy", name: "Fantasy" },
  { id: "adventure", name: "Adventure" },
]

export const mockStudios: StudioType[] = [
  {
    id: "epic-studios",
    name: "Epic Studios",
    username: "epicstudios",
    logo: "/placeholder.svg?height=80&width=80&text=ES",
    banner: "/placeholder.svg?height=300&width=1200&text=Epic+Studios+Banner",
    description:
      "Creating epic adventures and unforgettable stories since 2015. We specialize in high-budget action films and fantasy series.",
    verified: true,
    subscribers: 2400000,
    totalViews: 150000000,
    contentCount: 45,
    joinedDate: "2020-01-15",
    type: "Production Company",
    country: "United States",
    website: "https://epicstudios.com",
  },
  {
    id: "galaxy-pictures",
    name: "Galaxy Pictures",
    username: "galaxypictures",
    logo: "/placeholder.svg?height=80&width=80&text=GP",
    banner: "/placeholder.svg?height=300&width=1200&text=Galaxy+Pictures+Banner",
    description:
      "Exploring the cosmos through cinema. Award-winning sci-fi productions that push the boundaries of imagination.",
    verified: true,
    subscribers: 1800000,
    totalViews: 95000000,
    contentCount: 32,
    joinedDate: "2019-06-20",
    type: "Film Studio",
    country: "United Kingdom",
    website: "https://galaxypictures.co.uk",
  },
  {
    id: "streamflix-originals",
    name: "StreamFlix Originals",
    username: "streamflixoriginals",
    logo: "/placeholder.svg?height=80&width=80&text=SF",
    banner: "/placeholder.svg?height=300&width=1200&text=StreamFlix+Originals+Banner",
    description: "Premium original content exclusively for StreamFlix. From documentaries to blockbuster series.",
    verified: true,
    subscribers: 5200000,
    totalViews: 280000000,
    contentCount: 78,
    joinedDate: "2018-03-10",
    type: "Streaming Service",
    country: "United States",
    website: "https://streamflix.com/originals",
  },
]

export const mockVideos: VideoType[] = [
  {
    id: "featured",
    title: "the waiter",
    description:
      "An epic adventure across uncharted territories, where courage and friendship are tested to their limits.",
    thumbnail: "https://occ-0-5544-1167.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABd90hqawbNtkjwC9nFCGQBguzlJKjeCZQg-iowGrEGMbcUNjalQtHFjzQsRx9JbuvzUgS_aOc_dxKfth9TEbaVHTi_qlPI5lET8.jpg?r=903",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    duration: "2h 15m",
    year: 2023,
    rating: "PG-13",
    views: 1200000,
    categories: ["trending", "sci-fi", "adventure"],
    creator: {
      name: "StreamFlix Originals",
      avatar: "/placeholder.svg?height=48&width=48&text=SF",
      subscribers: 5200000,
    },
    studio: {
      name: "StreamFlix Originals",
      logo: "/placeholder.svg?height=48&width=48&text=SF",
      verified: true,
      type: "Streaming Service",
    },
  },
  {
    id: "1",
    title: "TO KILL A MONKEY",
    description: "A journey through the cosmos that challenges our understanding of time and space.",
    thumbnail: "https://occ-0-5544-1167.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABYqc4YMFmREYgbiQcZFWVz80oXXdqLggUYLLXChOSAAqwAptWVCD-997lH_m4B9pab4ajmPEDdtkEUM7G6G3wfZWnlHLeZ0hGb8.jpg?r=43f",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    duration: "1h 45m",
    year: 2022,
    rating: "PG-13",
    views: 850000,
    categories: ["sci-fi", "adventure"],
    creator: {
      name: "Galaxy Pictures",
      avatar: "/placeholder.svg?height=48&width=48&text=GP",
      subscribers: 1800000,
    },
    studio: {
      name: "Galaxy Pictures",
      logo: "/placeholder.svg?height=48&width=48&text=GP",
      verified: true,
      type: "Film Studio",
    },
  },
  {
    id: "2",
    title: "EVIL IS A LIAR",
    description: "A detective uncovers a conspiracy that goes deeper than anyone could have imagined.",
    thumbnail: "https://occ-0-5544-1167.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABW830RBNXGncvrp9qgIJ6lzyeo9C_ns7p9ZspCo2gMYmCaNdJ4go_XO2x-Y8Hi6NGKboUJWTWxI0pUYm3gxUYcC067yjSO-EgyI.jpg?r=280",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    duration: "2h 05m",
    year: 2023,
    rating: "R",
    views: 750000,
    categories: ["thriller", "drama"],
    creator: {
      name: "Mystery Box Productions",
      avatar: "/placeholder.svg?height=48&width=48&text=MB",
      subscribers: 980000,
    },
    studio: {
      name: "Mystery Box Productions",
      logo: "/placeholder.svg?height=48&width=48&text=MB",
      verified: false,
      type: "Independent Creator",
    },
  },
  {
    id: "3",
    title: "BEAUTY IN BLACK",
    description: "A comedy special that will have you in stitches from start to finish.",
    thumbnail: "https://occ-0-5544-1167.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABag2kEue9WidTfMbm1lCmdJh4AQCXw-BC5EFnEj4AqZs8vtfkIO1JX-Rj5R5Ftsf5RWbpFJ_MfKb4lkHE2DhzduqXj00CCVBoivaaCocvq3_tmRi1wOtG_ME4otynJotXTRE.jpg?r=553",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    duration: "1h 30m",
    year: 2023,
    rating: "PG-13",
    views: 1500000,
    categories: ["comedy", "trending"],
    creator: {
      name: "Comedy Central Studios",
      avatar: "/placeholder.svg?height=48&width=48&text=CC",
      subscribers: 3500000,
    },
    studio: {
      name: "Comedy Central Studios",
      logo: "/placeholder.svg?height=48&width=48&text=CC",
      verified: true,
      type: "TV Network",
    },
  },
  {
    id: "4",
    title: "WEDNESDAY",
    description: "Explore the mysteries of ancient civilizations and their architectural marvels.",
    thumbnail: "https://occ-0-5544-1167.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABeoohnxFnnker6egKMvwn6DeDzabFIl9ofD4lkS5kkiTPw-oLlWlg5EpZ55JS5_fxaNaPe3XQikLVASgsLctH9EVpSaAa9-tUfqu6sGD8TTXs0N1KWu9-ZWOWYdhA6HajAgl.jpg?r=f17",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    duration: "1h 55m",
    year: 2021,
    rating: "PG",
    views: 650000,
    categories: ["documentary", "adventure"],
    creator: {
      name: "History Channel",
      avatar: "/placeholder.svg?height=48&width=48&text=HC",
      subscribers: 2100000,
    },
    studio: {
      name: "History Channel",
      logo: "/placeholder.svg?height=48&width=48&text=HC",
      verified: true,
      type: "TV Network",
    },
  },
  {
    id: "5",
    title: "RUTH & BOAZ",
    description: "A touching love story that transcends time and distance.",
    thumbnail: "https://occ-0-5544-1167.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABdx_nf4ozRax17AaHDiwMcB8r0L7EotarC3IMBEvh1OZGsK2Cn1aihnzZSHApeZoBgFG1moFGRHo2Uq1FCpPWskYCWNelnm4hQ5dm2tOGSvRw4zZG9rM0iQTLGOJqdayPcDn.jpg?r=2ca",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    duration: "1h 50m",
    year: 2022,
    rating: "PG-13",
    views: 920000,
    categories: ["romance", "drama"],
    creator: {
      name: "Heartfelt Films",
      avatar: "/placeholder.svg?height=48&width=48&text=HF",
      subscribers: 1500000,
    },
    studio: {
      name: "Heartfelt Films",
      logo: "/placeholder.svg?height=48&width=48&text=HF",
      verified: true,
      type: "Production Company",
    },
  },
  {
    id: "6",
    title: "Bon Appetit your majesty",
    description: "A horror film that will keep you on the edge of your seat.",
    thumbnail: "https://occ-0-5544-1167.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABTpWXMLlwiesvueZTxXaoivv8g4l2ODEFMYPawEkoMrSWbUgLFWiN7FZGKgjuD7VF1FD91DOXr2JkIr4lhrakDf0b1j2MNnwCNOO7X5TBZ3TLmojDCeLiZeX9k2Mq4Zk8z07.jpg?r=0e7",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    duration: "1h 40m",
    year: 2023,
    rating: "R",
    views: 780000,
    categories: ["horror", "thriller"],
    creator: {
      name: "Nightmare Studios",
      avatar: "/placeholder.svg?height=48&width=48&text=NS",
      subscribers: 1800000,
    },
    studio: {
      name: "Nightmare Studios",
      logo: "/placeholder.svg?height=48&width=48&text=NS",
      verified: true,
      type: "Film Studio",
    },
  },
  {
    id: "7",
    title: "WAYWARD",
    description: "A documentary about the cutting edge of technology and its impact on society.",
    thumbnail: "https://occ-0-5544-1167.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABYXN81CvGNKQByY9wNOMbb2yJnsJzJIQW1Tc8Eyl5GdctEYpSqFO33WiVkYs2YX_7BTAfV2Rd1ZUmJX3tiA8xy8k-etQQzOkPIDE_NYYeeLD6ubKvWmeAHm4CTukCKDqA-yc.jpg?r=0d3",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    duration: "1h 25m",
    year: 2023,
    rating: "PG",
    views: 550000,
    categories: ["documentary", "trending"],
    creator: {
      name: "Tech Insights",
      avatar: "/placeholder.svg?height=48&width=48&text=TI",
      subscribers: 1200000,
    },
    studio: {
      name: "Tech Insights",
      logo: "/placeholder.svg?height=48&width=48&text=TI",
      verified: false,
      type: "Documentary Producer",
    },
  },
  {
    id: "8",
    title: "Animated Dreams",
    description: "A heartwarming animated film about following your dreams.",
    thumbnail: "/placeholder.svg?height=300&width=500&text=Animated+Dreams",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    duration: "1h 35m",
    year: 2022,
    rating: "G",
    views: 1100000,
    categories: ["animation", "family"],
    creator: {
      name: "Dream Works Animation",
      avatar: "/placeholder.svg?height=48&width=48&text=DW",
      subscribers: 2800000,
    },
    studio: {
      name: "Dream Works Animation",
      logo: "/placeholder.svg?height=48&width=48&text=DW",
      verified: true,
      type: "Animation Studio",
    },
  },
  {
    id: "9",
    title: "Action Heroes",
    description: "An action-packed adventure with stunning visual effects and heart-stopping stunts.",
    thumbnail: "/placeholder.svg?height=300&width=500&text=Action+Heroes",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    duration: "2h 10m",
    year: 2023,
    rating: "PG-13",
    views: 1300000,
    categories: ["action", "adventure", "trending"],
    creator: {
      name: "Epic Studios",
      avatar: "/placeholder.svg?height=48&width=48&text=ES",
      subscribers: 2400000,
    },
    studio: {
      name: "Epic Studios",
      logo: "/placeholder.svg?height=48&width=48&text=ES",
      verified: true,
      type: "Production Company",
    },
  },
  {
    id: "10",
    title: "Fantasy Realms",
    description: "Enter a world of magic and wonder in this epic fantasy adventure.",
    thumbnail: "/placeholder.svg?height=300&width=500&text=Fantasy+Realms",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
    duration: "2h 05m",
    year: 2022,
    rating: "PG",
    views: 950000,
    categories: ["fantasy", "adventure"],
    creator: {
      name: "Magical Productions",
      avatar: "/placeholder.svg?height=48&width=48&text=MP",
      subscribers: 1900000,
    },
    studio: {
      name: "Magical Productions",
      logo: "/placeholder.svg?height=48&width=48&text=MP",
      verified: true,
      type: "Production Company",
    },
  },
]

export const mockComments: CommentType[] = [
  {
    id: "1",
    user: {
      name: "JohnDoe",
      avatar: "/placeholder.svg?height=40&width=40&text=JD",
    },
    text: "This is an amazing video! I really enjoyed watching it.",
    likes: 24,
    timestamp: "2 days ago",
  },
  {
    id: "2",
    user: {
      name: "FilmFan2023",
      avatar: "/placeholder.svg?height=40&width=40&text=FF",
    },
    text: "The cinematography in this is absolutely stunning. Can't wait for the sequel!",
    likes: 42,
    timestamp: "1 week ago",
  },
  {
    id: "3",
    user: {
      name: "MovieCritic",
      avatar: "/placeholder.svg?height=40&width=40&text=MC",
    },
    text: "While the visuals are impressive, I felt the story could have been developed better.",
    likes: 8,
    timestamp: "3 days ago",
  },
  {
    id: "4",
    user: {
      name: "CasualViewer",
      avatar: "/placeholder.svg?height=40&width=40&text=CV",
    },
    text: "Perfect for a weekend watch. Loved the characters and the plot twists!",
    likes: 17,
    timestamp: "5 days ago",
  },
  {
    id: "5",
    user: {
      name: "TechEnthusiast",
      avatar: "/placeholder.svg?height=40&width=40&text=TE",
    },
    text: "The special effects in this are groundbreaking. How did they even do that?",
    likes: 31,
    timestamp: "1 day ago",
  },
]
